/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:08b9dd9c-8d9e-4838-ac5a-49ee8b79170f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kwFtlUind",
    "aws_user_pools_web_client_id": "1j78gn3t0n4opr482p4iufq3pa",
    "oauth": {}
};


export default awsmobile;
